# yaml-language-server: $schema=https://json-schema.axonivy.com/app/12.0.0/variables.json
# == Variables ==
# 
# You can define here your project Variables.
#
Variables:
  # All variables related to the SRF Weather connector
  SrfWeatherConnector:
    # For testing you can use the following Variable to refer to the testing Mock API under: 'http://localhost:8081/designer/api/weatherMock'
    # Url: http://localhost:8081/designer/api/weatherMock

        # Your Access Token for SRF weather connector
    # This token serves as your authentication key for accessing the SRF API.
    # [password]
    Token: "Bearer <Your Srf Weather API Token>"
