/*
 * SRF Weather
 * SRF Meteo serves weather forecast for over 100'000 locations within Switzerland
 *
 * OpenAPI spec version: 2.0.0
 * Contact: api@srgssr.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.srgssr.api.srf.meteo.v2.client;

import java.util.Objects;
import java.util.Arrays;
import ch.srgssr.api.srf.meteo.v2.client.Color;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.time.OffsetDateTime;
/**
 * DayForecastInterval
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-08-07T13:49:17.515284800+02:00[Europe/Zurich]")
public class DayForecastInterval {
  @JsonProperty("date_time")
  private OffsetDateTime dateTime = null;

  @JsonProperty("symbol_code")
  private Integer symbolCode = null;

  @JsonProperty("symbol24_code")
  private Integer symbol24Code = null;

  @JsonProperty("PROBPCP_PERCENT")
  private Integer PROBPCP_PERCENT = null;

  @JsonProperty("RRR_MM")
  private Double RRR_MM = null;

  @JsonProperty("FF_KMH")
  private Integer FF_KMH = null;

  @JsonProperty("FX_KMH")
  private Integer FX_KMH = null;

  @JsonProperty("DD_DEG")
  private Integer DD_DEG = null;

  @JsonProperty("SUNSET")
  private OffsetDateTime SUNSET = null;

  @JsonProperty("SUNRISE")
  private OffsetDateTime SUNRISE = null;

  @JsonProperty("SUN_H")
  private Integer SUN_H = null;

  @JsonProperty("UVI")
  private Integer UVI = null;

  @JsonProperty("TX_C")
  private Integer TX_C = null;

  @JsonProperty("TN_C")
  private Integer TN_C = null;

  @JsonProperty("min_color")
  private Color minColor = null;

  @JsonProperty("max_color")
  private Color maxColor = null;

  public DayForecastInterval dateTime(OffsetDateTime dateTime) {
    this.dateTime = dateTime;
    return this;
  }

   /**
   * Get dateTime
   * @return dateTime
  **/
  public OffsetDateTime getDateTime() {
    return dateTime;
  }

  public void setDateTime(OffsetDateTime dateTime) {
    this.dateTime = dateTime;
  }

  public DayForecastInterval symbolCode(Integer symbolCode) {
    this.symbolCode = symbolCode;
    return this;
  }

   /**
   * Get symbolCode
   * @return symbolCode
  **/
  public Integer getSymbolCode() {
    return symbolCode;
  }

  public void setSymbolCode(Integer symbolCode) {
    this.symbolCode = symbolCode;
  }

  public DayForecastInterval symbol24Code(Integer symbol24Code) {
    this.symbol24Code = symbol24Code;
    return this;
  }

   /**
   * Get symbol24Code
   * @return symbol24Code
  **/
  public Integer getSymbol24Code() {
    return symbol24Code;
  }

  public void setSymbol24Code(Integer symbol24Code) {
    this.symbol24Code = symbol24Code;
  }

  public DayForecastInterval PROBPCP_PERCENT(Integer PROBPCP_PERCENT) {
    this.PROBPCP_PERCENT = PROBPCP_PERCENT;
    return this;
  }

   /**
   * probability of rain in %
   * @return PROBPCP_PERCENT
  **/
  public Integer getPROBPCPPERCENT() {
    return PROBPCP_PERCENT;
  }

  public void setPROBPCPPERCENT(Integer PROBPCP_PERCENT) {
    this.PROBPCP_PERCENT = PROBPCP_PERCENT;
  }

  public DayForecastInterval RRR_MM(Double RRR_MM) {
    this.RRR_MM = RRR_MM;
    return this;
  }

   /**
   * total rainfall in mm
   * @return RRR_MM
  **/
  public Double getRRRMM() {
    return RRR_MM;
  }

  public void setRRRMM(Double RRR_MM) {
    this.RRR_MM = RRR_MM;
  }

  public DayForecastInterval FF_KMH(Integer FF_KMH) {
    this.FF_KMH = FF_KMH;
    return this;
  }

   /**
   * avg. wind speed in km/h
   * @return FF_KMH
  **/
  public Integer getFFKMH() {
    return FF_KMH;
  }

  public void setFFKMH(Integer FF_KMH) {
    this.FF_KMH = FF_KMH;
  }

  public DayForecastInterval FX_KMH(Integer FX_KMH) {
    this.FX_KMH = FX_KMH;
    return this;
  }

   /**
   * gust speed in km/h
   * @return FX_KMH
  **/
  public Integer getFXKMH() {
    return FX_KMH;
  }

  public void setFXKMH(Integer FX_KMH) {
    this.FX_KMH = FX_KMH;
  }

  public DayForecastInterval DD_DEG(Integer DD_DEG) {
    this.DD_DEG = DD_DEG;
    return this;
  }

   /**
   * direction of wind, -1 means: turning winds
   * @return DD_DEG
  **/
  public Integer getDDDEG() {
    return DD_DEG;
  }

  public void setDDDEG(Integer DD_DEG) {
    this.DD_DEG = DD_DEG;
  }

  public DayForecastInterval SUNSET(OffsetDateTime SUNSET) {
    this.SUNSET = SUNSET;
    return this;
  }

   /**
   * datetime of sunset, null if no sunset on that point/day
   * @return SUNSET
  **/
  public OffsetDateTime getSUNSET() {
    return SUNSET;
  }

  public void setSUNSET(OffsetDateTime SUNSET) {
    this.SUNSET = SUNSET;
  }

  public DayForecastInterval SUNRISE(OffsetDateTime SUNRISE) {
    this.SUNRISE = SUNRISE;
    return this;
  }

   /**
   * datetime of sunrise, null if no sunrise on that point/day
   * @return SUNRISE
  **/
  public OffsetDateTime getSUNRISE() {
    return SUNRISE;
  }

  public void setSUNRISE(OffsetDateTime SUNRISE) {
    this.SUNRISE = SUNRISE;
  }

  public DayForecastInterval SUN_H(Integer SUN_H) {
    this.SUN_H = SUN_H;
    return this;
  }

   /**
   * hours of sunshine
   * minimum: 0
   * maximum: 25
   * @return SUN_H
  **/
  public Integer getSUNH() {
    return SUN_H;
  }

  public void setSUNH(Integer SUN_H) {
    this.SUN_H = SUN_H;
  }

  public DayForecastInterval UVI(Integer UVI) {
    this.UVI = UVI;
    return this;
  }

   /**
   * UV index
   * minimum: 0
   * maximum: 20
   * @return UVI
  **/
  public Integer getUVI() {
    return UVI;
  }

  public void setUVI(Integer UVI) {
    this.UVI = UVI;
  }

  public DayForecastInterval TX_C(Integer TX_C) {
    this.TX_C = TX_C;
    return this;
  }

   /**
   * expected max temperature in celsius
   * @return TX_C
  **/
  public Integer getTXC() {
    return TX_C;
  }

  public void setTXC(Integer TX_C) {
    this.TX_C = TX_C;
  }

  public DayForecastInterval TN_C(Integer TN_C) {
    this.TN_C = TN_C;
    return this;
  }

   /**
   * expected min temperature in celsius
   * @return TN_C
  **/
  public Integer getTNC() {
    return TN_C;
  }

  public void setTNC(Integer TN_C) {
    this.TN_C = TN_C;
  }

  public DayForecastInterval minColor(Color minColor) {
    this.minColor = minColor;
    return this;
  }

   /**
   * Get minColor
   * @return minColor
  **/
  public Color getMinColor() {
    return minColor;
  }

  public void setMinColor(Color minColor) {
    this.minColor = minColor;
  }

  public DayForecastInterval maxColor(Color maxColor) {
    this.maxColor = maxColor;
    return this;
  }

   /**
   * Get maxColor
   * @return maxColor
  **/
  public Color getMaxColor() {
    return maxColor;
  }

  public void setMaxColor(Color maxColor) {
    this.maxColor = maxColor;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DayForecastInterval dayForecastInterval = (DayForecastInterval) o;
    return Objects.equals(this.dateTime, dayForecastInterval.dateTime) &&
        Objects.equals(this.symbolCode, dayForecastInterval.symbolCode) &&
        Objects.equals(this.symbol24Code, dayForecastInterval.symbol24Code) &&
        Objects.equals(this.PROBPCP_PERCENT, dayForecastInterval.PROBPCP_PERCENT) &&
        Objects.equals(this.RRR_MM, dayForecastInterval.RRR_MM) &&
        Objects.equals(this.FF_KMH, dayForecastInterval.FF_KMH) &&
        Objects.equals(this.FX_KMH, dayForecastInterval.FX_KMH) &&
        Objects.equals(this.DD_DEG, dayForecastInterval.DD_DEG) &&
        Objects.equals(this.SUNSET, dayForecastInterval.SUNSET) &&
        Objects.equals(this.SUNRISE, dayForecastInterval.SUNRISE) &&
        Objects.equals(this.SUN_H, dayForecastInterval.SUN_H) &&
        Objects.equals(this.UVI, dayForecastInterval.UVI) &&
        Objects.equals(this.TX_C, dayForecastInterval.TX_C) &&
        Objects.equals(this.TN_C, dayForecastInterval.TN_C) &&
        Objects.equals(this.minColor, dayForecastInterval.minColor) &&
        Objects.equals(this.maxColor, dayForecastInterval.maxColor);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dateTime, symbolCode, symbol24Code, PROBPCP_PERCENT, RRR_MM, FF_KMH, FX_KMH, DD_DEG, SUNSET, SUNRISE, SUN_H, UVI, TX_C, TN_C, minColor, maxColor);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DayForecastInterval {\n");
    
    sb.append("    dateTime: ").append(toIndentedString(dateTime)).append("\n");
    sb.append("    symbolCode: ").append(toIndentedString(symbolCode)).append("\n");
    sb.append("    symbol24Code: ").append(toIndentedString(symbol24Code)).append("\n");
    sb.append("    PROBPCP_PERCENT: ").append(toIndentedString(PROBPCP_PERCENT)).append("\n");
    sb.append("    RRR_MM: ").append(toIndentedString(RRR_MM)).append("\n");
    sb.append("    FF_KMH: ").append(toIndentedString(FF_KMH)).append("\n");
    sb.append("    FX_KMH: ").append(toIndentedString(FX_KMH)).append("\n");
    sb.append("    DD_DEG: ").append(toIndentedString(DD_DEG)).append("\n");
    sb.append("    SUNSET: ").append(toIndentedString(SUNSET)).append("\n");
    sb.append("    SUNRISE: ").append(toIndentedString(SUNRISE)).append("\n");
    sb.append("    SUN_H: ").append(toIndentedString(SUN_H)).append("\n");
    sb.append("    UVI: ").append(toIndentedString(UVI)).append("\n");
    sb.append("    TX_C: ").append(toIndentedString(TX_C)).append("\n");
    sb.append("    TN_C: ").append(toIndentedString(TN_C)).append("\n");
    sb.append("    minColor: ").append(toIndentedString(minColor)).append("\n");
    sb.append("    maxColor: ").append(toIndentedString(maxColor)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
