/*
 * SRF Weather
 * SRF Meteo serves weather forecast for over 100'000 locations within Switzerland
 *
 * OpenAPI spec version: 2.0.0
 * Contact: api@srgssr.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.srgssr.api.srf.meteo.v2.client;

import java.util.Objects;
import java.util.Arrays;
import ch.srgssr.api.srf.meteo.v2.client.DayForecastInterval;
import ch.srgssr.api.srf.meteo.v2.client.Geolocation;
import ch.srgssr.api.srf.meteo.v2.client.OneHourForecastInterval;
import ch.srgssr.api.srf.meteo.v2.client.ThreeHourForecastInterval;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * ForecastPointWeek
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-08-07T13:49:17.515284800+02:00[Europe/Zurich]")
public class ForecastPointWeek {
  @JsonProperty("days")
  private List<DayForecastInterval> days = new ArrayList<>();

  @JsonProperty("three_hours")
  private List<ThreeHourForecastInterval> threeHours = new ArrayList<>();

  @JsonProperty("hours")
  private List<OneHourForecastInterval> hours = new ArrayList<>();

  @JsonProperty("geolocation")
  private Geolocation geolocation = null;

  public ForecastPointWeek days(List<DayForecastInterval> days) {
    this.days = days;
    return this;
  }

  public ForecastPointWeek addDaysItem(DayForecastInterval daysItem) {
    this.days.add(daysItem);
    return this;
  }

   /**
   * Get days
   * @return days
  **/
  public List<DayForecastInterval> getDays() {
    return days;
  }

  public void setDays(List<DayForecastInterval> days) {
    this.days = days;
  }

  public ForecastPointWeek threeHours(List<ThreeHourForecastInterval> threeHours) {
    this.threeHours = threeHours;
    return this;
  }

  public ForecastPointWeek addThreeHoursItem(ThreeHourForecastInterval threeHoursItem) {
    this.threeHours.add(threeHoursItem);
    return this;
  }

   /**
   * Get threeHours
   * @return threeHours
  **/
  public List<ThreeHourForecastInterval> getThreeHours() {
    return threeHours;
  }

  public void setThreeHours(List<ThreeHourForecastInterval> threeHours) {
    this.threeHours = threeHours;
  }

  public ForecastPointWeek hours(List<OneHourForecastInterval> hours) {
    this.hours = hours;
    return this;
  }

  public ForecastPointWeek addHoursItem(OneHourForecastInterval hoursItem) {
    this.hours.add(hoursItem);
    return this;
  }

   /**
   * Get hours
   * @return hours
  **/
  public List<OneHourForecastInterval> getHours() {
    return hours;
  }

  public void setHours(List<OneHourForecastInterval> hours) {
    this.hours = hours;
  }

  public ForecastPointWeek geolocation(Geolocation geolocation) {
    this.geolocation = geolocation;
    return this;
  }

   /**
   * Get geolocation
   * @return geolocation
  **/
  public Geolocation getGeolocation() {
    return geolocation;
  }

  public void setGeolocation(Geolocation geolocation) {
    this.geolocation = geolocation;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ForecastPointWeek forecastPointWeek = (ForecastPointWeek) o;
    return Objects.equals(this.days, forecastPointWeek.days) &&
        Objects.equals(this.threeHours, forecastPointWeek.threeHours) &&
        Objects.equals(this.hours, forecastPointWeek.hours) &&
        Objects.equals(this.geolocation, forecastPointWeek.geolocation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(days, threeHours, hours, geolocation);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ForecastPointWeek {\n");
    
    sb.append("    days: ").append(toIndentedString(days)).append("\n");
    sb.append("    threeHours: ").append(toIndentedString(threeHours)).append("\n");
    sb.append("    hours: ").append(toIndentedString(hours)).append("\n");
    sb.append("    geolocation: ").append(toIndentedString(geolocation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
