/*
 * SRF Weather
 * SRF Meteo serves weather forecast for over 100'000 locations within Switzerland
 *
 * OpenAPI spec version: 2.0.0
 * Contact: api@srgssr.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.srgssr.api.srf.meteo.v2.client;

import java.util.Objects;
import java.util.Arrays;
import ch.srgssr.api.srf.meteo.v2.client.GeolocationName;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * Geolocation
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-08-07T13:49:17.515284800+02:00[Europe/Zurich]")
public class Geolocation {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("lat")
  private Double lat = null;

  @JsonProperty("lon")
  private Double lon = null;

  @JsonProperty("station_id")
  private String stationId = null;

  @JsonProperty("timezone")
  private String timezone = null;

  @JsonProperty("default_name")
  private String defaultName = null;

  @JsonProperty("alarm_region_id")
  private String alarmRegionId = null;

  @JsonProperty("alarm_region_name")
  private String alarmRegionName = null;

  @JsonProperty("district")
  private String district = null;

  @JsonProperty("geolocation_names")
  private List<GeolocationName> geolocationNames = null;

  public Geolocation id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Geolocation lat(Double lat) {
    this.lat = lat;
    return this;
  }

   /**
   * Get lat
   * @return lat
  **/
  public Double getLat() {
    return lat;
  }

  public void setLat(Double lat) {
    this.lat = lat;
  }

  public Geolocation lon(Double lon) {
    this.lon = lon;
    return this;
  }

   /**
   * Get lon
   * @return lon
  **/
  public Double getLon() {
    return lon;
  }

  public void setLon(Double lon) {
    this.lon = lon;
  }

  public Geolocation stationId(String stationId) {
    this.stationId = stationId;
    return this;
  }

   /**
   * Get stationId
   * @return stationId
  **/
  public String getStationId() {
    return stationId;
  }

  public void setStationId(String stationId) {
    this.stationId = stationId;
  }

  public Geolocation timezone(String timezone) {
    this.timezone = timezone;
    return this;
  }

   /**
   * Get timezone
   * @return timezone
  **/
  public String getTimezone() {
    return timezone;
  }

  public void setTimezone(String timezone) {
    this.timezone = timezone;
  }

  public Geolocation defaultName(String defaultName) {
    this.defaultName = defaultName;
    return this;
  }

   /**
   * Get defaultName
   * @return defaultName
  **/
  public String getDefaultName() {
    return defaultName;
  }

  public void setDefaultName(String defaultName) {
    this.defaultName = defaultName;
  }

  public Geolocation alarmRegionId(String alarmRegionId) {
    this.alarmRegionId = alarmRegionId;
    return this;
  }

   /**
   * only swiss (or nearby) forecasts
   * @return alarmRegionId
  **/
  public String getAlarmRegionId() {
    return alarmRegionId;
  }

  public void setAlarmRegionId(String alarmRegionId) {
    this.alarmRegionId = alarmRegionId;
  }

  public Geolocation alarmRegionName(String alarmRegionName) {
    this.alarmRegionName = alarmRegionName;
    return this;
  }

   /**
   * only on swiss (or nearby) forecsats
   * @return alarmRegionName
  **/
  public String getAlarmRegionName() {
    return alarmRegionName;
  }

  public void setAlarmRegionName(String alarmRegionName) {
    this.alarmRegionName = alarmRegionName;
  }

  public Geolocation district(String district) {
    this.district = district;
    return this;
  }

   /**
   * Get district
   * @return district
  **/
  public String getDistrict() {
    return district;
  }

  public void setDistrict(String district) {
    this.district = district;
  }

  public Geolocation geolocationNames(List<GeolocationName> geolocationNames) {
    this.geolocationNames = geolocationNames;
    return this;
  }

  public Geolocation addGeolocationNamesItem(GeolocationName geolocationNamesItem) {
    if (this.geolocationNames == null) {
      this.geolocationNames = new ArrayList<>();
    }
    this.geolocationNames.add(geolocationNamesItem);
    return this;
  }

   /**
   * Get geolocationNames
   * @return geolocationNames
  **/
  public List<GeolocationName> getGeolocationNames() {
    return geolocationNames;
  }

  public void setGeolocationNames(List<GeolocationName> geolocationNames) {
    this.geolocationNames = geolocationNames;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Geolocation geolocation = (Geolocation) o;
    return Objects.equals(this.id, geolocation.id) &&
        Objects.equals(this.lat, geolocation.lat) &&
        Objects.equals(this.lon, geolocation.lon) &&
        Objects.equals(this.stationId, geolocation.stationId) &&
        Objects.equals(this.timezone, geolocation.timezone) &&
        Objects.equals(this.defaultName, geolocation.defaultName) &&
        Objects.equals(this.alarmRegionId, geolocation.alarmRegionId) &&
        Objects.equals(this.alarmRegionName, geolocation.alarmRegionName) &&
        Objects.equals(this.district, geolocation.district) &&
        Objects.equals(this.geolocationNames, geolocation.geolocationNames);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, lat, lon, stationId, timezone, defaultName, alarmRegionId, alarmRegionName, district, geolocationNames);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Geolocation {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    lat: ").append(toIndentedString(lat)).append("\n");
    sb.append("    lon: ").append(toIndentedString(lon)).append("\n");
    sb.append("    stationId: ").append(toIndentedString(stationId)).append("\n");
    sb.append("    timezone: ").append(toIndentedString(timezone)).append("\n");
    sb.append("    defaultName: ").append(toIndentedString(defaultName)).append("\n");
    sb.append("    alarmRegionId: ").append(toIndentedString(alarmRegionId)).append("\n");
    sb.append("    alarmRegionName: ").append(toIndentedString(alarmRegionName)).append("\n");
    sb.append("    district: ").append(toIndentedString(district)).append("\n");
    sb.append("    geolocationNames: ").append(toIndentedString(geolocationNames)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
