/*
 * SRF Weather
 * SRF Meteo serves weather forecast for over 100'000 locations within Switzerland
 *
 * OpenAPI spec version: 2.0.0
 * Contact: api@srgssr.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.srgssr.api.srf.meteo.v2.client;

import java.util.Objects;
import java.util.Arrays;
import ch.srgssr.api.srf.meteo.v2.client.Geolocation;
import ch.srgssr.api.srf.meteo.v2.client.PoiType;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * GeolocationName
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-08-07T13:49:17.515284800+02:00[Europe/Zurich]")
public class GeolocationName {
  @JsonProperty("description_short")
  private String descriptionShort = null;

  @JsonProperty("description_long")
  private String descriptionLong = null;

  @JsonProperty("id")
  private String id = null;

  @JsonProperty("geolocation")
  private Geolocation geolocation = null;

  @JsonProperty("location_id")
  private String locationId = null;

  @JsonProperty("type")
  private String type = null;

  @JsonProperty("poi_type")
  private PoiType poiType = null;

  @JsonProperty("language")
  private Integer language = null;

  @JsonProperty("translation_type")
  private String translationType = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("country")
  private String country = null;

  @JsonProperty("province")
  private String province = null;

  @JsonProperty("inhabitants")
  private Integer inhabitants = null;

  @JsonProperty("height")
  private Integer height = null;

  @JsonProperty("plz")
  private Integer plz = null;

  @JsonProperty("ch")
  private Integer ch = null;

  public GeolocationName descriptionShort(String descriptionShort) {
    this.descriptionShort = descriptionShort;
    return this;
  }

   /**
   * Get descriptionShort
   * @return descriptionShort
  **/
  public String getDescriptionShort() {
    return descriptionShort;
  }

  public void setDescriptionShort(String descriptionShort) {
    this.descriptionShort = descriptionShort;
  }

  public GeolocationName descriptionLong(String descriptionLong) {
    this.descriptionLong = descriptionLong;
    return this;
  }

   /**
   * Get descriptionLong
   * @return descriptionLong
  **/
  public String getDescriptionLong() {
    return descriptionLong;
  }

  public void setDescriptionLong(String descriptionLong) {
    this.descriptionLong = descriptionLong;
  }

  public GeolocationName id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public GeolocationName geolocation(Geolocation geolocation) {
    this.geolocation = geolocation;
    return this;
  }

   /**
   * Get geolocation
   * @return geolocation
  **/
  public Geolocation getGeolocation() {
    return geolocation;
  }

  public void setGeolocation(Geolocation geolocation) {
    this.geolocation = geolocation;
  }

  public GeolocationName locationId(String locationId) {
    this.locationId = locationId;
    return this;
  }

   /**
   * Get locationId
   * @return locationId
  **/
  public String getLocationId() {
    return locationId;
  }

  public void setLocationId(String locationId) {
    this.locationId = locationId;
  }

  public GeolocationName type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public GeolocationName poiType(PoiType poiType) {
    this.poiType = poiType;
    return this;
  }

   /**
   * Get poiType
   * @return poiType
  **/
  public PoiType getPoiType() {
    return poiType;
  }

  public void setPoiType(PoiType poiType) {
    this.poiType = poiType;
  }

  public GeolocationName language(Integer language) {
    this.language = language;
    return this;
  }

   /**
   * Get language
   * @return language
  **/
  public Integer getLanguage() {
    return language;
  }

  public void setLanguage(Integer language) {
    this.language = language;
  }

  public GeolocationName translationType(String translationType) {
    this.translationType = translationType;
    return this;
  }

   /**
   * Get translationType
   * @return translationType
  **/
  public String getTranslationType() {
    return translationType;
  }

  public void setTranslationType(String translationType) {
    this.translationType = translationType;
  }

  public GeolocationName name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public GeolocationName country(String country) {
    this.country = country;
    return this;
  }

   /**
   * Get country
   * @return country
  **/
  public String getCountry() {
    return country;
  }

  public void setCountry(String country) {
    this.country = country;
  }

  public GeolocationName province(String province) {
    this.province = province;
    return this;
  }

   /**
   * Get province
   * @return province
  **/
  public String getProvince() {
    return province;
  }

  public void setProvince(String province) {
    this.province = province;
  }

  public GeolocationName inhabitants(Integer inhabitants) {
    this.inhabitants = inhabitants;
    return this;
  }

   /**
   * Get inhabitants
   * @return inhabitants
  **/
  public Integer getInhabitants() {
    return inhabitants;
  }

  public void setInhabitants(Integer inhabitants) {
    this.inhabitants = inhabitants;
  }

  public GeolocationName height(Integer height) {
    this.height = height;
    return this;
  }

   /**
   * Get height
   * @return height
  **/
  public Integer getHeight() {
    return height;
  }

  public void setHeight(Integer height) {
    this.height = height;
  }

  public GeolocationName plz(Integer plz) {
    this.plz = plz;
    return this;
  }

   /**
   * Get plz
   * @return plz
  **/
  public Integer getPlz() {
    return plz;
  }

  public void setPlz(Integer plz) {
    this.plz = plz;
  }

  public GeolocationName ch(Integer ch) {
    this.ch = ch;
    return this;
  }

   /**
   * Get ch
   * @return ch
  **/
  public Integer getCh() {
    return ch;
  }

  public void setCh(Integer ch) {
    this.ch = ch;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GeolocationName geolocationName = (GeolocationName) o;
    return Objects.equals(this.descriptionShort, geolocationName.descriptionShort) &&
        Objects.equals(this.descriptionLong, geolocationName.descriptionLong) &&
        Objects.equals(this.id, geolocationName.id) &&
        Objects.equals(this.geolocation, geolocationName.geolocation) &&
        Objects.equals(this.locationId, geolocationName.locationId) &&
        Objects.equals(this.type, geolocationName.type) &&
        Objects.equals(this.poiType, geolocationName.poiType) &&
        Objects.equals(this.language, geolocationName.language) &&
        Objects.equals(this.translationType, geolocationName.translationType) &&
        Objects.equals(this.name, geolocationName.name) &&
        Objects.equals(this.country, geolocationName.country) &&
        Objects.equals(this.province, geolocationName.province) &&
        Objects.equals(this.inhabitants, geolocationName.inhabitants) &&
        Objects.equals(this.height, geolocationName.height) &&
        Objects.equals(this.plz, geolocationName.plz) &&
        Objects.equals(this.ch, geolocationName.ch);
  }

  @Override
  public int hashCode() {
    return Objects.hash(descriptionShort, descriptionLong, id, geolocation, locationId, type, poiType, language, translationType, name, country, province, inhabitants, height, plz, ch);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GeolocationName {\n");
    
    sb.append("    descriptionShort: ").append(toIndentedString(descriptionShort)).append("\n");
    sb.append("    descriptionLong: ").append(toIndentedString(descriptionLong)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    geolocation: ").append(toIndentedString(geolocation)).append("\n");
    sb.append("    locationId: ").append(toIndentedString(locationId)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    poiType: ").append(toIndentedString(poiType)).append("\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    translationType: ").append(toIndentedString(translationType)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    province: ").append(toIndentedString(province)).append("\n");
    sb.append("    inhabitants: ").append(toIndentedString(inhabitants)).append("\n");
    sb.append("    height: ").append(toIndentedString(height)).append("\n");
    sb.append("    plz: ").append(toIndentedString(plz)).append("\n");
    sb.append("    ch: ").append(toIndentedString(ch)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
