/*
 * SRF Weather
 * SRF Meteo serves weather forecast for over 100'000 locations within Switzerland
 *
 * OpenAPI spec version: 2.0.0
 * Contact: api@srgssr.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.srgssr.api.srf.meteo.v2.client;

import java.util.Objects;
import java.util.Arrays;
import ch.srgssr.api.srf.meteo.v2.client.GeolocationName1;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * GeolocationsID
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-08-07T13:49:17.515284800+02:00[Europe/Zurich]")
public class GeolocationsID {
  @JsonProperty("id")
  private Integer id = null;

  @JsonProperty("lat")
  private Integer lat = null;

  @JsonProperty("lon")
  private Integer lon = null;

  @JsonProperty("station_id")
  private String stationId = null;

  @JsonProperty("timezone")
  private String timezone = null;

  @JsonProperty("default_name")
  private String defaultName = null;

  @JsonProperty("district")
  private String district = null;

  @JsonProperty("geolocation_names")
  private List<GeolocationName1> geolocationNames = new ArrayList<>();

  public GeolocationsID id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public GeolocationsID lat(Integer lat) {
    this.lat = lat;
    return this;
  }

   /**
   * Get lat
   * @return lat
  **/
  public Integer getLat() {
    return lat;
  }

  public void setLat(Integer lat) {
    this.lat = lat;
  }

  public GeolocationsID lon(Integer lon) {
    this.lon = lon;
    return this;
  }

   /**
   * Get lon
   * @return lon
  **/
  public Integer getLon() {
    return lon;
  }

  public void setLon(Integer lon) {
    this.lon = lon;
  }

  public GeolocationsID stationId(String stationId) {
    this.stationId = stationId;
    return this;
  }

   /**
   * Get stationId
   * @return stationId
  **/
  public String getStationId() {
    return stationId;
  }

  public void setStationId(String stationId) {
    this.stationId = stationId;
  }

  public GeolocationsID timezone(String timezone) {
    this.timezone = timezone;
    return this;
  }

   /**
   * Get timezone
   * @return timezone
  **/
  public String getTimezone() {
    return timezone;
  }

  public void setTimezone(String timezone) {
    this.timezone = timezone;
  }

  public GeolocationsID defaultName(String defaultName) {
    this.defaultName = defaultName;
    return this;
  }

   /**
   * Get defaultName
   * @return defaultName
  **/
  public String getDefaultName() {
    return defaultName;
  }

  public void setDefaultName(String defaultName) {
    this.defaultName = defaultName;
  }

  public GeolocationsID district(String district) {
    this.district = district;
    return this;
  }

   /**
   * Get district
   * @return district
  **/
  public String getDistrict() {
    return district;
  }

  public void setDistrict(String district) {
    this.district = district;
  }

  public GeolocationsID geolocationNames(List<GeolocationName1> geolocationNames) {
    this.geolocationNames = geolocationNames;
    return this;
  }

  public GeolocationsID addGeolocationNamesItem(GeolocationName1 geolocationNamesItem) {
    this.geolocationNames.add(geolocationNamesItem);
    return this;
  }

   /**
   * Get geolocationNames
   * @return geolocationNames
  **/
  public List<GeolocationName1> getGeolocationNames() {
    return geolocationNames;
  }

  public void setGeolocationNames(List<GeolocationName1> geolocationNames) {
    this.geolocationNames = geolocationNames;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GeolocationsID geolocationsID = (GeolocationsID) o;
    return Objects.equals(this.id, geolocationsID.id) &&
        Objects.equals(this.lat, geolocationsID.lat) &&
        Objects.equals(this.lon, geolocationsID.lon) &&
        Objects.equals(this.stationId, geolocationsID.stationId) &&
        Objects.equals(this.timezone, geolocationsID.timezone) &&
        Objects.equals(this.defaultName, geolocationsID.defaultName) &&
        Objects.equals(this.district, geolocationsID.district) &&
        Objects.equals(this.geolocationNames, geolocationsID.geolocationNames);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, lat, lon, stationId, timezone, defaultName, district, geolocationNames);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GeolocationsID {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    lat: ").append(toIndentedString(lat)).append("\n");
    sb.append("    lon: ").append(toIndentedString(lon)).append("\n");
    sb.append("    stationId: ").append(toIndentedString(stationId)).append("\n");
    sb.append("    timezone: ").append(toIndentedString(timezone)).append("\n");
    sb.append("    defaultName: ").append(toIndentedString(defaultName)).append("\n");
    sb.append("    district: ").append(toIndentedString(district)).append("\n");
    sb.append("    geolocationNames: ").append(toIndentedString(geolocationNames)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
