/*
 * SRF Weather
 * SRF Meteo serves weather forecast for over 100'000 locations within Switzerland
 *
 * OpenAPI spec version: 2.0.0
 * Contact: api@srgssr.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.srgssr.api.srf.meteo.v2.client;

import java.util.Objects;
import java.util.Arrays;
import ch.srgssr.api.srf.meteo.v2.client.PoiType;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * GeolocationName1
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-08-07T13:49:17.515284800+02:00[Europe/Zurich]")
public class GeolocationName1 {
  @JsonProperty("district")
  private String district = null;

  @JsonProperty("id")
  private String id = null;

  @JsonProperty("location_id")
  private Integer locationId = null;

  @JsonProperty("type")
  private String type = null;

  @JsonProperty("poi_type")
  private PoiType poiType = null;

  @JsonProperty("language")
  private String language = null;

  @JsonProperty("translation_type")
  private String translationType = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("country")
  private String country = null;

  @JsonProperty("province")
  private String province = null;

  @JsonProperty("inhabitants")
  private Integer inhabitants = null;

  @JsonProperty("height")
  private Integer height = null;

  @JsonProperty("ch")
  private Integer ch = null;

  public GeolocationName1 district(String district) {
    this.district = district;
    return this;
  }

   /**
   * Get district
   * @return district
  **/
  public String getDistrict() {
    return district;
  }

  public void setDistrict(String district) {
    this.district = district;
  }

  public GeolocationName1 id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public GeolocationName1 locationId(Integer locationId) {
    this.locationId = locationId;
    return this;
  }

   /**
   * Get locationId
   * @return locationId
  **/
  public Integer getLocationId() {
    return locationId;
  }

  public void setLocationId(Integer locationId) {
    this.locationId = locationId;
  }

  public GeolocationName1 type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public GeolocationName1 poiType(PoiType poiType) {
    this.poiType = poiType;
    return this;
  }

   /**
   * Get poiType
   * @return poiType
  **/
  public PoiType getPoiType() {
    return poiType;
  }

  public void setPoiType(PoiType poiType) {
    this.poiType = poiType;
  }

  public GeolocationName1 language(String language) {
    this.language = language;
    return this;
  }

   /**
   * Get language
   * @return language
  **/
  public String getLanguage() {
    return language;
  }

  public void setLanguage(String language) {
    this.language = language;
  }

  public GeolocationName1 translationType(String translationType) {
    this.translationType = translationType;
    return this;
  }

   /**
   * Get translationType
   * @return translationType
  **/
  public String getTranslationType() {
    return translationType;
  }

  public void setTranslationType(String translationType) {
    this.translationType = translationType;
  }

  public GeolocationName1 name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public GeolocationName1 country(String country) {
    this.country = country;
    return this;
  }

   /**
   * Get country
   * @return country
  **/
  public String getCountry() {
    return country;
  }

  public void setCountry(String country) {
    this.country = country;
  }

  public GeolocationName1 province(String province) {
    this.province = province;
    return this;
  }

   /**
   * Get province
   * @return province
  **/
  public String getProvince() {
    return province;
  }

  public void setProvince(String province) {
    this.province = province;
  }

  public GeolocationName1 inhabitants(Integer inhabitants) {
    this.inhabitants = inhabitants;
    return this;
  }

   /**
   * Get inhabitants
   * @return inhabitants
  **/
  public Integer getInhabitants() {
    return inhabitants;
  }

  public void setInhabitants(Integer inhabitants) {
    this.inhabitants = inhabitants;
  }

  public GeolocationName1 height(Integer height) {
    this.height = height;
    return this;
  }

   /**
   * Get height
   * @return height
  **/
  public Integer getHeight() {
    return height;
  }

  public void setHeight(Integer height) {
    this.height = height;
  }

  public GeolocationName1 ch(Integer ch) {
    this.ch = ch;
    return this;
  }

   /**
   * Get ch
   * @return ch
  **/
  public Integer getCh() {
    return ch;
  }

  public void setCh(Integer ch) {
    this.ch = ch;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GeolocationName1 geolocationName1 = (GeolocationName1) o;
    return Objects.equals(this.district, geolocationName1.district) &&
        Objects.equals(this.id, geolocationName1.id) &&
        Objects.equals(this.locationId, geolocationName1.locationId) &&
        Objects.equals(this.type, geolocationName1.type) &&
        Objects.equals(this.poiType, geolocationName1.poiType) &&
        Objects.equals(this.language, geolocationName1.language) &&
        Objects.equals(this.translationType, geolocationName1.translationType) &&
        Objects.equals(this.name, geolocationName1.name) &&
        Objects.equals(this.country, geolocationName1.country) &&
        Objects.equals(this.province, geolocationName1.province) &&
        Objects.equals(this.inhabitants, geolocationName1.inhabitants) &&
        Objects.equals(this.height, geolocationName1.height) &&
        Objects.equals(this.ch, geolocationName1.ch);
  }

  @Override
  public int hashCode() {
    return Objects.hash(district, id, locationId, type, poiType, language, translationType, name, country, province, inhabitants, height, ch);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GeolocationName1 {\n");
    
    sb.append("    district: ").append(toIndentedString(district)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    locationId: ").append(toIndentedString(locationId)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    poiType: ").append(toIndentedString(poiType)).append("\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    translationType: ").append(toIndentedString(translationType)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    province: ").append(toIndentedString(province)).append("\n");
    sb.append("    inhabitants: ").append(toIndentedString(inhabitants)).append("\n");
    sb.append("    height: ").append(toIndentedString(height)).append("\n");
    sb.append("    ch: ").append(toIndentedString(ch)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
