/*
 * SRF Weather
 * SRF Meteo serves weather forecast for over 100'000 locations within Switzerland
 *
 * OpenAPI spec version: 2.0.0
 * Contact: api@srgssr.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.srgssr.api.srf.meteo.v2.client;

import java.util.Objects;
import java.util.Arrays;
import ch.srgssr.api.srf.meteo.v2.client.Geolocation;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * GeolocationNamesSearch
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-08-07T13:49:17.515284800+02:00[Europe/Zurich]")
public class GeolocationNamesSearch {
  @JsonProperty("district")
  private String district = null;

  @JsonProperty("id")
  private Integer id = null;

  @JsonProperty("geolocation")
  private Geolocation geolocation = null;

  @JsonProperty("location_id")
  private Integer locationId = null;

  @JsonProperty("type")
  private String type = null;

  @JsonProperty("default_name")
  private String defaultName = null;

  @JsonProperty("language")
  private String language = null;

  @JsonProperty("translation_type")
  private String translationType = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("country")
  private String country = null;

  @JsonProperty("province")
  private String province = null;

  @JsonProperty("inhabitants")
  private String inhabitants = null;

  @JsonProperty("height")
  private Integer height = null;

  @JsonProperty("ch")
  private String ch = null;

  public GeolocationNamesSearch district(String district) {
    this.district = district;
    return this;
  }

   /**
   * Get district
   * @return district
  **/
  public String getDistrict() {
    return district;
  }

  public void setDistrict(String district) {
    this.district = district;
  }

  public GeolocationNamesSearch id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public GeolocationNamesSearch geolocation(Geolocation geolocation) {
    this.geolocation = geolocation;
    return this;
  }

   /**
   * Get geolocation
   * @return geolocation
  **/
  public Geolocation getGeolocation() {
    return geolocation;
  }

  public void setGeolocation(Geolocation geolocation) {
    this.geolocation = geolocation;
  }

  public GeolocationNamesSearch locationId(Integer locationId) {
    this.locationId = locationId;
    return this;
  }

   /**
   * Get locationId
   * @return locationId
  **/
  public Integer getLocationId() {
    return locationId;
  }

  public void setLocationId(Integer locationId) {
    this.locationId = locationId;
  }

  public GeolocationNamesSearch type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public GeolocationNamesSearch defaultName(String defaultName) {
    this.defaultName = defaultName;
    return this;
  }

   /**
   * Get defaultName
   * @return defaultName
  **/
  public String getDefaultName() {
    return defaultName;
  }

  public void setDefaultName(String defaultName) {
    this.defaultName = defaultName;
  }

  public GeolocationNamesSearch language(String language) {
    this.language = language;
    return this;
  }

   /**
   * Get language
   * @return language
  **/
  public String getLanguage() {
    return language;
  }

  public void setLanguage(String language) {
    this.language = language;
  }

  public GeolocationNamesSearch translationType(String translationType) {
    this.translationType = translationType;
    return this;
  }

   /**
   * Get translationType
   * @return translationType
  **/
  public String getTranslationType() {
    return translationType;
  }

  public void setTranslationType(String translationType) {
    this.translationType = translationType;
  }

  public GeolocationNamesSearch name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public GeolocationNamesSearch country(String country) {
    this.country = country;
    return this;
  }

   /**
   * Get country
   * @return country
  **/
  public String getCountry() {
    return country;
  }

  public void setCountry(String country) {
    this.country = country;
  }

  public GeolocationNamesSearch province(String province) {
    this.province = province;
    return this;
  }

   /**
   * Get province
   * @return province
  **/
  public String getProvince() {
    return province;
  }

  public void setProvince(String province) {
    this.province = province;
  }

  public GeolocationNamesSearch inhabitants(String inhabitants) {
    this.inhabitants = inhabitants;
    return this;
  }

   /**
   * Get inhabitants
   * @return inhabitants
  **/
  public String getInhabitants() {
    return inhabitants;
  }

  public void setInhabitants(String inhabitants) {
    this.inhabitants = inhabitants;
  }

  public GeolocationNamesSearch height(Integer height) {
    this.height = height;
    return this;
  }

   /**
   * Get height
   * @return height
  **/
  public Integer getHeight() {
    return height;
  }

  public void setHeight(Integer height) {
    this.height = height;
  }

  public GeolocationNamesSearch ch(String ch) {
    this.ch = ch;
    return this;
  }

   /**
   * Get ch
   * @return ch
  **/
  public String getCh() {
    return ch;
  }

  public void setCh(String ch) {
    this.ch = ch;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GeolocationNamesSearch geolocationNamesSearch = (GeolocationNamesSearch) o;
    return Objects.equals(this.district, geolocationNamesSearch.district) &&
        Objects.equals(this.id, geolocationNamesSearch.id) &&
        Objects.equals(this.geolocation, geolocationNamesSearch.geolocation) &&
        Objects.equals(this.locationId, geolocationNamesSearch.locationId) &&
        Objects.equals(this.type, geolocationNamesSearch.type) &&
        Objects.equals(this.defaultName, geolocationNamesSearch.defaultName) &&
        Objects.equals(this.language, geolocationNamesSearch.language) &&
        Objects.equals(this.translationType, geolocationNamesSearch.translationType) &&
        Objects.equals(this.name, geolocationNamesSearch.name) &&
        Objects.equals(this.country, geolocationNamesSearch.country) &&
        Objects.equals(this.province, geolocationNamesSearch.province) &&
        Objects.equals(this.inhabitants, geolocationNamesSearch.inhabitants) &&
        Objects.equals(this.height, geolocationNamesSearch.height) &&
        Objects.equals(this.ch, geolocationNamesSearch.ch);
  }

  @Override
  public int hashCode() {
    return Objects.hash(district, id, geolocation, locationId, type, defaultName, language, translationType, name, country, province, inhabitants, height, ch);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GeolocationNamesSearch {\n");
    
    sb.append("    district: ").append(toIndentedString(district)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    geolocation: ").append(toIndentedString(geolocation)).append("\n");
    sb.append("    locationId: ").append(toIndentedString(locationId)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    defaultName: ").append(toIndentedString(defaultName)).append("\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    translationType: ").append(toIndentedString(translationType)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    province: ").append(toIndentedString(province)).append("\n");
    sb.append("    inhabitants: ").append(toIndentedString(inhabitants)).append("\n");
    sb.append("    height: ").append(toIndentedString(height)).append("\n");
    sb.append("    ch: ").append(toIndentedString(ch)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
