/*
 * SRF Weather
 * SRF Meteo serves weather forecast for over 100'000 locations within Switzerland
 *
 * OpenAPI spec version: 2.0.0
 * Contact: api@srgssr.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.srgssr.api.srf.meteo.v2.client;

import java.util.Objects;
import java.util.Arrays;
import ch.srgssr.api.srf.meteo.v2.client.Color;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.time.OffsetDateTime;
/**
 * ThreeHourForecastInterval
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-08-07T13:49:17.515284800+02:00[Europe/Zurich]")
public class ThreeHourForecastInterval {
  @JsonProperty("date_time")
  private OffsetDateTime dateTime = null;

  @JsonProperty("symbol_code")
  private Integer symbolCode = null;

  @JsonProperty("symbol24_code")
  private Integer symbol24Code = null;

  @JsonProperty("PROBPCP_PERCENT")
  private Integer PROBPCP_PERCENT = null;

  @JsonProperty("RRR_MM")
  private Double RRR_MM = null;

  @JsonProperty("FF_KMH")
  private Integer FF_KMH = null;

  @JsonProperty("FX_KMH")
  private Integer FX_KMH = null;

  @JsonProperty("DD_DEG")
  private Integer DD_DEG = null;

  @JsonProperty("TTT_C")
  private Integer TTT_C = null;

  @JsonProperty("TTL_C")
  private Double TTL_C = null;

  @JsonProperty("TTH_C")
  private Double TTH_C = null;

  @JsonProperty("DEWPOINT_C")
  private Double DEWPOINT_C = null;

  @JsonProperty("RELHUM_PERCENT")
  private Integer RELHUM_PERCENT = null;

  @JsonProperty("FRESHSNOW_CM")
  private Integer FRESHSNOW_CM = null;

  @JsonProperty("PRESSURE_HPA")
  private Integer PRESSURE_HPA = null;

  @JsonProperty("SUN_MIN")
  private Integer SUN_MIN = null;

  @JsonProperty("IRRADIANCE_WM2")
  private Integer irRADIANCEWM2 = null;

  @JsonProperty("TTTFEEL_C")
  private Integer TTTFEEL_C = null;

  @JsonProperty("cur_color")
  private Color curColor = null;

  public ThreeHourForecastInterval dateTime(OffsetDateTime dateTime) {
    this.dateTime = dateTime;
    return this;
  }

   /**
   * Get dateTime
   * @return dateTime
  **/
  public OffsetDateTime getDateTime() {
    return dateTime;
  }

  public void setDateTime(OffsetDateTime dateTime) {
    this.dateTime = dateTime;
  }

  public ThreeHourForecastInterval symbolCode(Integer symbolCode) {
    this.symbolCode = symbolCode;
    return this;
  }

   /**
   * Get symbolCode
   * @return symbolCode
  **/
  public Integer getSymbolCode() {
    return symbolCode;
  }

  public void setSymbolCode(Integer symbolCode) {
    this.symbolCode = symbolCode;
  }

  public ThreeHourForecastInterval symbol24Code(Integer symbol24Code) {
    this.symbol24Code = symbol24Code;
    return this;
  }

   /**
   * Get symbol24Code
   * @return symbol24Code
  **/
  public Integer getSymbol24Code() {
    return symbol24Code;
  }

  public void setSymbol24Code(Integer symbol24Code) {
    this.symbol24Code = symbol24Code;
  }

  public ThreeHourForecastInterval PROBPCP_PERCENT(Integer PROBPCP_PERCENT) {
    this.PROBPCP_PERCENT = PROBPCP_PERCENT;
    return this;
  }

   /**
   * probability of rain in %
   * @return PROBPCP_PERCENT
  **/
  public Integer getPROBPCPPERCENT() {
    return PROBPCP_PERCENT;
  }

  public void setPROBPCPPERCENT(Integer PROBPCP_PERCENT) {
    this.PROBPCP_PERCENT = PROBPCP_PERCENT;
  }

  public ThreeHourForecastInterval RRR_MM(Double RRR_MM) {
    this.RRR_MM = RRR_MM;
    return this;
  }

   /**
   * total rainfall in mm
   * @return RRR_MM
  **/
  public Double getRRRMM() {
    return RRR_MM;
  }

  public void setRRRMM(Double RRR_MM) {
    this.RRR_MM = RRR_MM;
  }

  public ThreeHourForecastInterval FF_KMH(Integer FF_KMH) {
    this.FF_KMH = FF_KMH;
    return this;
  }

   /**
   * avg. wind speed in km/h
   * @return FF_KMH
  **/
  public Integer getFFKMH() {
    return FF_KMH;
  }

  public void setFFKMH(Integer FF_KMH) {
    this.FF_KMH = FF_KMH;
  }

  public ThreeHourForecastInterval FX_KMH(Integer FX_KMH) {
    this.FX_KMH = FX_KMH;
    return this;
  }

   /**
   * gust speed in km/h
   * @return FX_KMH
  **/
  public Integer getFXKMH() {
    return FX_KMH;
  }

  public void setFXKMH(Integer FX_KMH) {
    this.FX_KMH = FX_KMH;
  }

  public ThreeHourForecastInterval DD_DEG(Integer DD_DEG) {
    this.DD_DEG = DD_DEG;
    return this;
  }

   /**
   * direction of wind, -1 means: turning winds
   * @return DD_DEG
  **/
  public Integer getDDDEG() {
    return DD_DEG;
  }

  public void setDDDEG(Integer DD_DEG) {
    this.DD_DEG = DD_DEG;
  }

  public ThreeHourForecastInterval TTT_C(Integer TTT_C) {
    this.TTT_C = TTT_C;
    return this;
  }

   /**
   * expected temperature in celsius
   * @return TTT_C
  **/
  public Integer getTTTC() {
    return TTT_C;
  }

  public void setTTTC(Integer TTT_C) {
    this.TTT_C = TTT_C;
  }

  public ThreeHourForecastInterval TTL_C(Double TTL_C) {
    this.TTL_C = TTL_C;
    return this;
  }

   /**
   * lower bound of expected temperature range in celsius
   * @return TTL_C
  **/
  public Double getTTLC() {
    return TTL_C;
  }

  public void setTTLC(Double TTL_C) {
    this.TTL_C = TTL_C;
  }

  public ThreeHourForecastInterval TTH_C(Double TTH_C) {
    this.TTH_C = TTH_C;
    return this;
  }

   /**
   * upper bound of expected temperature range in celsius
   * @return TTH_C
  **/
  public Double getTTHC() {
    return TTH_C;
  }

  public void setTTHC(Double TTH_C) {
    this.TTH_C = TTH_C;
  }

  public ThreeHourForecastInterval DEWPOINT_C(Double DEWPOINT_C) {
    this.DEWPOINT_C = DEWPOINT_C;
    return this;
  }

   /**
   * Dewpoint
   * @return DEWPOINT_C
  **/
  public Double getDEWPOINTC() {
    return DEWPOINT_C;
  }

  public void setDEWPOINTC(Double DEWPOINT_C) {
    this.DEWPOINT_C = DEWPOINT_C;
  }

  public ThreeHourForecastInterval RELHUM_PERCENT(Integer RELHUM_PERCENT) {
    this.RELHUM_PERCENT = RELHUM_PERCENT;
    return this;
  }

   /**
   * Relative air humidity
   * @return RELHUM_PERCENT
  **/
  public Integer getRELHUMPERCENT() {
    return RELHUM_PERCENT;
  }

  public void setRELHUMPERCENT(Integer RELHUM_PERCENT) {
    this.RELHUM_PERCENT = RELHUM_PERCENT;
  }

  public ThreeHourForecastInterval FRESHSNOW_CM(Integer FRESHSNOW_CM) {
    this.FRESHSNOW_CM = FRESHSNOW_CM;
    return this;
  }

   /**
   * Fresh snow in the hour before event
   * @return FRESHSNOW_CM
  **/
  public Integer getFRESHSNOWCM() {
    return FRESHSNOW_CM;
  }

  public void setFRESHSNOWCM(Integer FRESHSNOW_CM) {
    this.FRESHSNOW_CM = FRESHSNOW_CM;
  }

  public ThreeHourForecastInterval PRESSURE_HPA(Integer PRESSURE_HPA) {
    this.PRESSURE_HPA = PRESSURE_HPA;
    return this;
  }

   /**
   * Barometric pressure
   * @return PRESSURE_HPA
  **/
  public Integer getPRESSUREHPA() {
    return PRESSURE_HPA;
  }

  public void setPRESSUREHPA(Integer PRESSURE_HPA) {
    this.PRESSURE_HPA = PRESSURE_HPA;
  }

  public ThreeHourForecastInterval SUN_MIN(Integer SUN_MIN) {
    this.SUN_MIN = SUN_MIN;
    return this;
  }

   /**
   * Sunshine duration in the hour before event
   * @return SUN_MIN
  **/
  public Integer getSUNMIN() {
    return SUN_MIN;
  }

  public void setSUNMIN(Integer SUN_MIN) {
    this.SUN_MIN = SUN_MIN;
  }

  public ThreeHourForecastInterval irRADIANCEWM2(Integer irRADIANCEWM2) {
    this.irRADIANCEWM2 = irRADIANCEWM2;
    return this;
  }

   /**
   * Global irradiance
   * @return irRADIANCEWM2
  **/
  public Integer getIrRADIANCEWM2() {
    return irRADIANCEWM2;
  }

  public void setIrRADIANCEWM2(Integer irRADIANCEWM2) {
    this.irRADIANCEWM2 = irRADIANCEWM2;
  }

  public ThreeHourForecastInterval TTTFEEL_C(Integer TTTFEEL_C) {
    this.TTTFEEL_C = TTTFEEL_C;
    return this;
  }

   /**
   * felt temperature
   * @return TTTFEEL_C
  **/
  public Integer getTTTFEELC() {
    return TTTFEEL_C;
  }

  public void setTTTFEELC(Integer TTTFEEL_C) {
    this.TTTFEEL_C = TTTFEEL_C;
  }

  public ThreeHourForecastInterval curColor(Color curColor) {
    this.curColor = curColor;
    return this;
  }

   /**
   * Get curColor
   * @return curColor
  **/
  public Color getCurColor() {
    return curColor;
  }

  public void setCurColor(Color curColor) {
    this.curColor = curColor;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ThreeHourForecastInterval threeHourForecastInterval = (ThreeHourForecastInterval) o;
    return Objects.equals(this.dateTime, threeHourForecastInterval.dateTime) &&
        Objects.equals(this.symbolCode, threeHourForecastInterval.symbolCode) &&
        Objects.equals(this.symbol24Code, threeHourForecastInterval.symbol24Code) &&
        Objects.equals(this.PROBPCP_PERCENT, threeHourForecastInterval.PROBPCP_PERCENT) &&
        Objects.equals(this.RRR_MM, threeHourForecastInterval.RRR_MM) &&
        Objects.equals(this.FF_KMH, threeHourForecastInterval.FF_KMH) &&
        Objects.equals(this.FX_KMH, threeHourForecastInterval.FX_KMH) &&
        Objects.equals(this.DD_DEG, threeHourForecastInterval.DD_DEG) &&
        Objects.equals(this.TTT_C, threeHourForecastInterval.TTT_C) &&
        Objects.equals(this.TTL_C, threeHourForecastInterval.TTL_C) &&
        Objects.equals(this.TTH_C, threeHourForecastInterval.TTH_C) &&
        Objects.equals(this.DEWPOINT_C, threeHourForecastInterval.DEWPOINT_C) &&
        Objects.equals(this.RELHUM_PERCENT, threeHourForecastInterval.RELHUM_PERCENT) &&
        Objects.equals(this.FRESHSNOW_CM, threeHourForecastInterval.FRESHSNOW_CM) &&
        Objects.equals(this.PRESSURE_HPA, threeHourForecastInterval.PRESSURE_HPA) &&
        Objects.equals(this.SUN_MIN, threeHourForecastInterval.SUN_MIN) &&
        Objects.equals(this.irRADIANCEWM2, threeHourForecastInterval.irRADIANCEWM2) &&
        Objects.equals(this.TTTFEEL_C, threeHourForecastInterval.TTTFEEL_C) &&
        Objects.equals(this.curColor, threeHourForecastInterval.curColor);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dateTime, symbolCode, symbol24Code, PROBPCP_PERCENT, RRR_MM, FF_KMH, FX_KMH, DD_DEG, TTT_C, TTL_C, TTH_C, DEWPOINT_C, RELHUM_PERCENT, FRESHSNOW_CM, PRESSURE_HPA, SUN_MIN, irRADIANCEWM2, TTTFEEL_C, curColor);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ThreeHourForecastInterval {\n");
    
    sb.append("    dateTime: ").append(toIndentedString(dateTime)).append("\n");
    sb.append("    symbolCode: ").append(toIndentedString(symbolCode)).append("\n");
    sb.append("    symbol24Code: ").append(toIndentedString(symbol24Code)).append("\n");
    sb.append("    PROBPCP_PERCENT: ").append(toIndentedString(PROBPCP_PERCENT)).append("\n");
    sb.append("    RRR_MM: ").append(toIndentedString(RRR_MM)).append("\n");
    sb.append("    FF_KMH: ").append(toIndentedString(FF_KMH)).append("\n");
    sb.append("    FX_KMH: ").append(toIndentedString(FX_KMH)).append("\n");
    sb.append("    DD_DEG: ").append(toIndentedString(DD_DEG)).append("\n");
    sb.append("    TTT_C: ").append(toIndentedString(TTT_C)).append("\n");
    sb.append("    TTL_C: ").append(toIndentedString(TTL_C)).append("\n");
    sb.append("    TTH_C: ").append(toIndentedString(TTH_C)).append("\n");
    sb.append("    DEWPOINT_C: ").append(toIndentedString(DEWPOINT_C)).append("\n");
    sb.append("    RELHUM_PERCENT: ").append(toIndentedString(RELHUM_PERCENT)).append("\n");
    sb.append("    FRESHSNOW_CM: ").append(toIndentedString(FRESHSNOW_CM)).append("\n");
    sb.append("    PRESSURE_HPA: ").append(toIndentedString(PRESSURE_HPA)).append("\n");
    sb.append("    SUN_MIN: ").append(toIndentedString(SUN_MIN)).append("\n");
    sb.append("    irRADIANCEWM2: ").append(toIndentedString(irRADIANCEWM2)).append("\n");
    sb.append("    TTTFEEL_C: ").append(toIndentedString(TTTFEEL_C)).append("\n");
    sb.append("    curColor: ").append(toIndentedString(curColor)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
